name: presen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_easyloading: ^3.0.5
  sp_util: ^2.0.3      
  qr_flutter: ^4.0.0  
  qrscan: ^0.3.3
  intl: ^0.17.0
  date_time_picker: ^2.1.0      
  permission_handler: ^10.2.0
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

